# Generated by Django 5.0.7 on 2024-09-13 05:44

import products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('ALL', 'ALL'), ('Play Group', 'Play Group'), ('Pre-Primary 1', 'Pre-primary one'), ('Pre-Primary 2', 'Pre-primary two'), ('Grade 1', 'Grade One'), ('Grade 2', 'Grade Two'), ('Grade 3', 'Grade Three'), ('Grade 4', 'Grade Four'), ('Grade 5', 'Grade Five'), ('Grade 6', 'Grade Six'), ('Grade 7', 'Grade Seven'), ('Grade 8', 'Grade Eight'), ('Grade 9', 'Grade Nine'), ('Grade 10', 'Grade Ten'), ('Grade 11', 'Grade Eleven'), ('Grade 12', 'Grade Twelve')], default='pp1', max_length=20)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('substitutable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visibility', models.BooleanField(default=False)),
                ('stock_availability', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='res/default.jpg', null=True, upload_to=products.models.item_image_path)),
                ('subject', models.CharField(default='N/A', max_length=100)),
                ('publisher', models.CharField(default='N/A', max_length=100)),
                ('category', models.CharField(choices=[('Textbooks', 'Textbook'), ('Workbooks', 'Workbooks'), ('Exercise Books', 'Exercise Books'), ('Reference', 'Reference Books'), ('Teachers Guide', "Teacher's Guide"), ('Stationery', 'Stationery'), ('Storybooks', 'Storybook'), ('Electronics', 'Electronics'), ('Bags', 'Bags')], default='Textbooks', max_length=20)),
                ('grade', models.CharField(choices=[('ALL', 'ALL'), ('Play Group', 'Play Group'), ('Pre-Primary 1', 'Pre-primary one'), ('Pre-Primary 2', 'Pre-primary two'), ('Grade 1', 'Grade One'), ('Grade 2', 'Grade Two'), ('Grade 3', 'Grade Three'), ('Grade 4', 'Grade Four'), ('Grade 5', 'Grade Five'), ('Grade 6', 'Grade Six'), ('Grade 7', 'Grade Seven'), ('Grade 8', 'Grade Eight'), ('Grade 9', 'Grade Nine'), ('Grade 10', 'Grade Ten'), ('Grade 11', 'Grade Eleven'), ('Grade 12', 'Grade Twelve')], default='All', max_length=20)),
                ('study_level', models.CharField(choices=[('All', 'ALL'), ('ECDE & Pre-Primary', 'ECDE & Pre-Primary'), ('Primary School', 'Primary School'), ('Junior Secondary', 'Junior School'), ('Secondary School', 'Secondary School')], default='All', max_length=20)),
                ('curriculum', models.CharField(choices=[('CBC', 'CBC'), ('IGCSE', 'IGCSE'), ('ALL', 'ALL')], default='All', max_length=20)),
                ('cluster', models.CharField(default='Economy Pack', max_length=20)),
                ('tag', models.CharField(default='N/A', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
