# Generated by Django 5.0.7 on 2024-09-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='userManager.organization'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.collection'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('school', 'grade')},
        ),
    ]
