# Generated by Django 5.0.7 on 2024-09-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ISBN',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
