# Generated by Django 5.0.7 on 2024-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_isbn_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='study_level',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ECDE & Pre-Primary', 'ECDE & Pre-Primary'), ('Primary School', 'Primary School'), ('Junior School', 'Junior School'), ('Secondary School', 'Secondary School'), ('Higher Education', 'Higher Education')], default='All', max_length=20),
        ),
    ]
