# Generated by Django 5.0.7 on 2024-09-13 05:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order_cancellation_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cancellation Request',
                'verbose_name_plural': 'Cancellation Requests',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('failed', 'failed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stripe_id', models.CharField(blank=True, max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('receipient_name', models.CharField(max_length=100)),
                ('receipt_email', models.EmailField(max_length=100)),
                ('delivered', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('Play Group', 'Play Group'), ('Pre-Primary 1', 'Pre-primary one'), ('Pre-Primary 2', 'Pre-primary two'), ('Grade 1', 'Grade One'), ('Grade 2', 'Grade Two'), ('Grade 3', 'Grade Three'), ('Grade 4', 'Grade Four'), ('Grade 5', 'Grade Five'), ('Grade 6', 'Grade Six'), ('Grade 7', 'Grade Seven'), ('Grade 8', 'Grade Eight'), ('Grade 9', 'Grade Nine'), ('Grade 10', 'Grade Ten'), ('Grade 11', 'Grade Eleven'), ('Grade 12', 'Grade Twelve')], max_length=20)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
            },
        ),
    ]
