# Generated by Django 5.0.7 on 2024-09-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Checklist',
                'verbose_name_plural': 'Order Checklists',
            },
        ),
        migrations.CreateModel(
            name='OrderItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaged', models.BooleanField(default=False)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('order_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_checklists', to='order_tracking.orderchecklist')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_checklists', to='order.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Checklist',
                'verbose_name_plural': 'Order Item Checklists',
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('created', 'Order Created'), ('processing', 'Processing'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed')], max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Step',
                'verbose_name_plural': 'Order Steps',
                'ordering': ['timestamp'],
            },
        ),
    ]
