# Generated by Django 5.0.7 on 2024-09-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='userManager.organization'),
        ),
    ]
