# Generated by Django 5.0.7 on 2024-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('All', 'ALL'), ('ECDE & Pre-Primary', 'ECDE & Pre-Primary'), ('Primary School', 'Primary School'), ('Junior Secondary', 'Junior School'), ('Secondary School', 'Secondary School')], default='Private', max_length=50),
        ),
    ]
